[tool.poetry]
name = "chessmind"
version = "0.1.0"
description = ""
authors = ["Leo C. <leopold@lchappuis.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
websockets = "^11.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
